---
sidebar_position: 9
---

# notFound
调用该 `notFound()` 函数会引发 `NEXT_NOT_FOUND` 错误，并终止后续的路由处理。
通过指定一个 `not-found` 文件，当触发 `NEXT_NOT_FOUND` 错误时，会使用 `not found` UI 来优雅地处理此类错误。

```tsx
"use server"
import { notFound } from 'next/navigation'
 
async function fetchUser(id) {
    const res = await fetch('https://...')
    if (!res.ok) return undefined
    return res.json()
}

export default async function Profile({ params }) {
    const user = await fetchUser(params.id)
    
    if (!user) {
        notFound()
    }
    //   ...
}
```
